import { FrameDefinition } from "../framestypes";

export const movieHero3Actors: FrameDefinition = {
  id: "movie_hero 3_actors",
  displayName: "Hero (3-TL)-Actors",
  src: "/frames/purple.png",
  imageSource: "actors",
  positionMode: "absolute",
  maxAssets: 3,
  renderMode: "perSlot",
  canvas: {
    width: 2216,
    height: 1412,
  },
  imageSlots: [
    {
      id: "card1",
      x: 420,
      y: 170,
      width: 2000,
      height: 1200,
      rotation: 0,
      imageOffsetX: 30,
      imageOffsetY: 30,
      imageScale: 1,
      frameScale: 1,
    },
    {
      id: "card2",
      x: 150,
      y: 182,
      width: 1000,
      height: 600,
      rotation: 0,
      imageOffsetX: 15,
      imageOffsetY: 10,
      imageScale: 1,
      frameScale: 0.5,
    },
    {
      id: "card3",
      x: 710,
      y: 520,
      width: 1000,
      height: 590,
      rotation: 0,
      imageOffsetX: 20,
      imageOffsetY: 20,
      imageScale: 1,
      frameScale: 0.5,
    },
  ],
  placement: {
    mode: "width",
    anchor: "top",
    width: 600,
    transformOrigin: "center center",
  },
};
