import { FrameDefinition } from "../framestypes";

export const paperripScatter4Backdrops: FrameDefinition = {
  id:"paperrip_scatter_4_backdrops",
  displayName:    "Paper Rip Scatter (4) — Backdrop",
  positionMode:"absolute",
  src:    "/frames/paperrip.png",
  imageSource:    "backdrops",
  maxAssets:    4,
  renderMode:    "perSlot",
  canvas: {
    width: 4096,
    height: 4081,
  },
  imageSlots:[
    {
      id: "card1",
      x: 68,
      y: 708,
      width: 2286,
      height: 2674,
      imageOffsetX:77,
      imageOffsetY:55,
      imageScale:1.05,
      slotFrameScale: 1,
    },
  {
    id:"card2",
    x:80,
    y:330,
    width:2286,
    height:2674,
    rotation:12,
    imageOffsetX:77,
    imageOffsetY:55,
    imageScale:1.05,
    slotFrameScale: 1,
  },
  {
    id:"card3",
    x:500,
    y:350,
    width:2286,
    height:2674,
    rotation:-8,
    imageOffsetX:77,
    imageOffsetY:55,
    imageScale:1.05,
    slotFrameScale: 1,
  },
  {
    id:"card4",
    x:520,
    y:750,
    width:2286,
    height:2674,
    rotation:18,
    imageOffsetX:77,
    imageOffsetY:55,
    imageScale:1.05,
    slotFrameScale: 1,  
  },
],
  placement:{
    mode:"width",
    anchor:"center",
    width:400,
    transformOrigin:"center center",
  },
};
