import { FrameDefinition } from "../framestypes";

export const polaroidScatterActor: FrameDefinition = {
  id: "polaroid_scatter_actor",
  displayName: "Polaroid Scatter — Actors",
  positionMode: "absolute",
  src: "/frames/polaroid-classic.png",
  imageSource: "actors",
  maxAssets: 4,
  renderMode: "perSlot",
  canvas: {
    width: 1600,
    height: 2200,
  },
  imageSlots: [
    {
      id: "card1",
      x: -80,
      y: 520,
      width: 1380,
      height: 1390,
      rotation: -22,
      imageOffsetX: 20,
      imageOffsetY: 35,
      imageScale: 1.05,
    },
    {
      id: "card2",
      x: 180,
      y: 330,
      width: 1380,
      height: 1390,
      rotation: 12,
      imageOffsetX: 30,
      imageOffsetY: 30,
      imageScale: 1.03,
    },
    {
      id: "card3",
      x: 500,
      y: 500,
      width: 1380,
      height: 1390,
      rotation: -8,
      imageOffsetX: 15,
      imageOffsetY: 30,
      imageScale: 1.02,
    },
    {
      id: "card4",
      x: 780,
      y: 280,
      width: 1380,
      height: 1390,
      rotation: 18,
      imageOffsetX: 30,
      imageOffsetY: 20,
      imageScale: 1.04,
    },
  ],
  placement: {
    mode: "width",
    anchor: "center",
    width: 400,
    transformOrigin: "center center",
  },
};