import { VariantDefinition } from "../../variantstypes";

export const movieScatterActor: VariantDefinition = {
  id: "movie_scatter_actor",
  displayName: "Movie Strip Scatter — Actors",
  positionMode: "absolute",
  src: "/frames/singleframe.png",
  imageSource: "actors",
  maxAssets: 4,
  renderMode: "perSlot",
  canvas: {
    width: 1660,
    height: 1645,
  },
  imageSlots: [
    {
      id: "card1",
      x: 30,
      y: 520,
      width: 1600,
      height: 1200,
      rotation: -22,
      imageOffsetX: 2,
      imageOffsetY: 40,
      imageScale: 1,
    },
    {
      id: "card2",
      x: 230,
      y: 330,
      width: 1600,
      height: 1200,
      rotation: 12,
      imageOffsetX: 0,
      imageOffsetY: 37,
      imageScale: 1,
    },
    {
      id: "card3",
      x: 450,
      y: 500,
      width: 1600,
      height: 1200,
      rotation: -8,
      imageOffsetX: 3,
      imageOffsetY: 40,
      imageScale: 1,
    },
    {
      id: "card4",
      x: 700,
      y: 380,
      width: 1600,
      height: 1200,
      rotation: 18,
      imageOffsetX: 0,
      imageOffsetY: 37,
      imageScale: 1,
    },
  ],
  placement: {
    mode: "contain",
    anchor: "center",
    width: 300,
    transformOrigin: "center center",
  },
};
