"use client";

import { create } from "zustand";

/**

* =========================================================
* JELLYBACK STAGE 3 COMPOSITION STORE
* =========================================================
*
* PURPOSE
* ---
* Holds ONLY Stage 3 runtime state.
*
* Stage 2.5 owns:
* * metadata
* * actors
* * backdrops
* * assets
* * generated variants
*
* Stage 3 owns:
* * active variant selection
* * metadata bar style selection
*
* Stage 3 NEVER:
* * queries Jellyfin
* * enriches metadata
* * mutates the seed
* * performs composition decisions
*
* Seed enters once across the Border.
* Renderer consumes only what is stored here.
*
* =========================================================
  */

export type MetadataBarStyle =
| "dvdStrip"
| "steelBar"
| "minimal";

export type VariantLayer =
| "collage"
| "actors"
| "logo"
| "metadataBar";

export type CompositionStore = {
/**

* ---
* HYDRATED SEED
* ---

*/
seed: any | null;

/**

* ---
* ACTIVE VARIANT SELECTIONS
* ---
*
* Indexes into arrays generated by Stage 2.5.
  */
  active: {
  collage: number;
  actors: number;
  logo: number;
  metadataBar: number;
  };



/**

* ---
* METADATA BAR STYLE
* ---

*/
metadataBarStyle: MetadataBarStyle;

/**

* ---
* ACTIONS
* ---

*/
setSeed: (seed: any) => void;

nextVariant: (layer: VariantLayer) => void;

previousVariant: (layer: VariantLayer) => void;

setMetadataBarStyle: (
style: MetadataBarStyle
) => void;

reset: () => void;
};

export const useCompositionStore =
create<CompositionStore>((set, get) => ({
/**
* -----------------------------------------------------
* INITIAL STATE
* -----------------------------------------------------
*/
seed: null,


active: {
  collage: 0,
  actors: 0,
  logo: 0,
  metadataBar: 0,
},

metadataBarStyle: "dvdStrip",

/**
 * -----------------------------------------------------
 * SEED HYDRATION
 * -----------------------------------------------------
 */
setSeed: (seed) => {
  console.log(
    "[STAGE3 STORE] setSeed:",
    seed?.movieId
  );

  set({
    seed,
  });
},

/**
 * -----------------------------------------------------
 * VARIANT NAVIGATION
 * -----------------------------------------------------
 */
nextVariant: (layer) => {
  const state = get();

  const current = state.active[layer];

  console.log(
    "[STAGE3 STORE] nextVariant:",
    layer,
    current + 1
  );

  set({
    active: {
      ...state.active,
      [layer]: current + 1,
    },
  });
},

previousVariant: (layer) => {
  const state = get();

  const current = state.active[layer];

  set({
    active: {
      ...state.active,
      [layer]: Math.max(0, current - 1),
    },
  });
},

/**
 * -----------------------------------------------------
 * METADATA BAR
 * -----------------------------------------------------
 */
setMetadataBarStyle: (style) => {
  console.log(
    "[STAGE3 STORE] metadata style:",
    style
  );

  set({
    metadataBarStyle: style,
  });
},

/**
 * -----------------------------------------------------
 * RESET
 * -----------------------------------------------------
 */
reset: () => {
  console.log(
    "[STAGE3 STORE] reset"
  );

  set({
    seed: null,

    active: {
      collage: 0,
      actors: 0,
      logo: 0,
      metadataBar: 0,
    },

    metadataBarStyle: "dvdStrip",
  });
},


}));
export default useCompositionStore;
